# Generated by Django 3.2.19 on 2025-01-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chief', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chief.chief')),
            ],
        ),
    ]
